name: Обновление products.json

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install beautifulsoup4 requests

      - name: Clean HTML pages
        run: python data/clean_html_pages.py

      - name: Run parser & update products.json
        run: python data/auto_update_products.py

      - name: Commit changes if any
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/products.json
          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "chore: auto-update products.json [skip ci]"
          fi

      - name: Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
