# .github/workflows/update-products.yml
name: Авто-обновление продуктовых данных

on:
  # Раз в сутки и по ручному запуску
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  update-products:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Настроить Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Установить зависимости
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4

      - name: Запустить парсер
        run: python data/auto_update_products.py

      - name: Закоммитить и запушить обновлённый products.json
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          message: 'chore: авто-обновление data/products.json'
          add: 'data/products.json'
          push: true
