# .github/workflows/update_products.yml
name: Обновление products.json

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update-products:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: pip install requests beautifulsoup4

      - run: python data/auto_update_products.py

      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/products.json
          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "chore: auto-update products.json [skip ci]"
            git push origin main
          fi
