name: Обновление products.json

permissions:
  contents: write

on:
  schedule:
    # каждый день в 6:00 утра по UTC
    - cron: '0 6 * * *'
  workflow_dispatch: {}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Установить Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Установить зависимости
        run: |
          pip install requests beautifulsoup4 cloudscraper

      - name: Запустить сбор условий
        run: python data/auto_update_products.py

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/products.json
          git diff --quiet || git commit -m "chore: auto-update products.json [skip ci]"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
