name: Обновление products.json

permissions:
  contents: write

on:
  schedule:
    # каждый день в 06:00 UTC
    - cron: '0 6 * * *'
  workflow_dispatch: {}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 cloudscraper

      - name: Run updater
        run: python data/auto_update_products.py

      - name: Pull remote changes
        run: git pull --rebase origin main

      - name: Commit updated products.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/products.json
          git diff --quiet || git commit -m "chore: auto-update products.json [skip ci]"

      - name: Push changes
        run: git push origin HEAD:main
