# .github/workflows/update_products.yml
name: Обновление products.json

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Chromium & chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install deps
        run: pip install selenium beautifulsoup4

      - name: Run parser
        run: python data/auto_update_products.py

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # форсируем добавление игнорируемого файла
          git add -f data/products.json
          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "chore: auto-update products.json via Selenium CI"
            git push origin main
          fi
